<section class="content sticky-main" style="margin-top: 120px;">
    
<h1 class="align-center">Login</h1>

<hr />

<form method="post" novalidate="custom" style="width: 280px;">

    <fieldset class="cf" id="database-info">
        
        <div class="input-group cf">
            <input id="testes" type="text" name="username" autocorrect="off" autocapitalize="off" placeholder="Username" required>                  
        </div>
        <div class="input-group cf">
            <input type="password" name="password" placeholder="Password" required>                  
        </div>
        
        <div class="input-group">
            <button class="btn btn-success btn-center" type="submit" style="margin-top: 20px;" disabled>Login</button>  
        </div>
        
    </fieldset>
    
</form>

<hr />

</section>

<script>
    
$('form').on('submit', function(){
    
    if(this.checkValidity()) {
        var data = $(this).serialize();
        
        // fire off ajax
        $.ajax({
            type: 'POST',
            url: 'ajax/?admin=login.php',
            data: data,
            cache: false,
            dataType: 'json',
            success: function(response) {
                
                // reload on success
                if(response.success === true) {
                    window.location = window.location;
                }
                
                // display errors
                else {
                    console.log(response.error);
                }
            }
        });
        
    }    
    
    return false;
});

</script>