<div class="content">
    
<h2>Login</h2>

<form method="post" novalidate="custom">

    <fieldset class="cf" id="database-info">

        <hr style="margin-bottom: 60px" />
        
        <div class="input-group cf">
            <input id="testes" type="text" name="username" autocorrect="off" autocapitalize="off" placeholder="Username" required>                  
        </div>
        <div class="input-group cf">
            <input type="password" name="password" placeholder="Password" required>                  
        </div>
        
        <button class="btn btn-success btn-center" type="submit" style="margin-top: 20px;" disabled>Login</button>
           
        <hr style="margin-top: 60px" />
        
    </fieldset>
    
</form>

</div>

<script>
        
$('input').on('blur', function(){
    var valid = this.validity.valid;
    valid ? $(this).removeClass('invalid') : $(this).addClass('invalid');
}).on('keyup', function(){
    var valid = this.validity.valid;
    valid ? $(this).removeClass('invalid') : $(this).addClass('invalid');
    
    var form = document.getElementsByTagName('form');
    form[0].checkValidity() ?
        $('button[type="submit"]').removeAttr('disabled') :
        $('button[type="submit"]').attr('disabled','disabled');
});
    
$('form').on('submit', function(){
    
    if(this.checkValidity()) {
        var data = $(this).serialize();
        
        // fire off ajax
        $.ajax({
            type: 'POST',
            url: 'ajax/?admin=login.php',
            data: data,
            cache: false,
            dataType: 'json',
            success: function(response) {
                
                // reload on success
                if(response.success === true) {
                    window.location = window.location;
                }
                
                // display errors
                else {
                    console.log(response.error);
                }
            }
        });
        
    }    
    
    return false;
});

</script>