<div class="content">
    
<h2>Login</h2>

<form method="post" novalidate="custom">

    <fieldset class="cf" id="database-info">

        <hr style="margin-bottom: 60px" />
        
        <div class="input-group cf">
            <input name="username" autocorrect="off" autocapitalize="off" placeholder="Username">                  
        </div>
        <div class="input-group cf">
            <input type="password" name="password" placeholder="Password">                  
        </div>
        
        <button class="btn btn-success btn-center" type="submit" style="margin-top: 20px;">Login</button>
           
        <hr style="margin-top: 60px" />
        
    </fieldset>
    
</form>

</div>