<?php defined("PRIVATE") or die("Permission Denied. Cannot Access Directly."); ?>

<!doctype html>
<html lang="en-us">
    
<head>
    <meta charset="utf-8">
    <title>Datoid Admin</title>
    <meta name="robots" content="noindex, nofollow">

    <link rel="stylesheet" href="<?= URL::absolute('/css/main.css'); ?>">
    <link rel="stylesheet" href="<?= URL::relative(__FILE__,'../admin.css'); ?>">
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.js"><\/script>');</script>
</head>
    
<body>
    
    <h1><a href="<?= URL::absolute() ?>">Datoid</a>
        
<?php   if ($page == 'dashboard') {
            $name = explode(' ', Session::get('realname'));
?>
    
        <span class="pull-right">
            Hello, <?= $name[0]; ?>!
            <a class="btn" href="/admin?action=logout">log out</a>
        </span>
            
    
<?php } else { ?>
        
            <span class="pull-right"><?= $page; ?></span>
        
<?php } ?>
    
    </h1>