<?php defined("PRIVATE") or die("Permission Denied. Cannot Access Directly."); 

require PATH . 'app/admin/includes/admin-header.phtml';

?>

<section class="content sticky-main">
    <h1>Internal Server Error</h1>

    <p>An error occured while we were processing your request.</p>
    <p class="monospace"><small>Code: 500</small></p>
</section>

<?php

require PATH . 'app/admin/includes/admin-footer.phtml';

?>